# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
scrape: !include files/scrape.yaml
notify: !include files/notify.yaml
group: !include files/groups.yaml

homeassistant:
  allowlist_external_dirs:
    - "/config"

mqtt:
  sensor:
    - name: Server Battery
      default_entity_id: sensor.server_battery
      state_topic: &server_battery_topic "battery2mqtt/server/BAT0"
      value_template: "{{ value_json.capacity }}"
      unit_of_measurement: "%"
      json_attributes_topic: *server_battery_topic
      availability_topic: "battery2mqtt/server/status"
      device_class: battery
      unique_id: server_battery
