# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include files/automations.yaml
script: !include files/scripts.yaml
scene: !include files/scenes.yaml
scrape: !include files/scrape.yaml
notify: !include files/notify.yaml
group: !include files/groups.yaml

homeassistant:
  allowlist_external_dirs:
    - "/config"